INSERT INTO USERS (FIRST_NAME, LAST_NAME, PASSWORD, USERNAME) VALUES ('Admin', 'Adminsson', '$2a$11$lVnw9DS4d6fcB17R/OwIwujo8xgk6iuHpmZMeRcKe7.rT1Xp3gaAq', 'svenssonmc84@gmail.com')

INSERT INTO ROLE (NAME) VALUES ('ADMIN')
INSERT INTO ROLE (NAME) VALUES ('USER')

INSERT INTO USERS_ROLES VALUES (1L, 1L)
INSERT INTO USERS_ROLES VALUES (1L, 2L)